baseurl = "https://saliei.io"
languageCode = "en-us"
theme = "himin"
pagination.pagerSize = 10

[params]
  contentTypeName = "posts"
  defaultTheme = "light"
  showMenuItems = 5
  manuallyOrderedMenuItems = true
  showReadingTime = false

[languages]
  [languages.en.params]
    title = "Saeid Aliei"
    subtitle = "Saeid Aliei"
    keywords = ""
    copyright = ""
    menuMore = "Show more"
    writtenBy = " "
    readMore = "Read more"
    readOtherPosts = "Read other posts"
    newerPosts = "Newer posts"
    olderPosts = "Older posts"
    minuteReadingTime = "min read"
    dateFormatSingle = "02-01-2006"
    dateFormatList = "02-01"

    [languages.en.params.logo]
      logoText = "Saeid Aliei"
      logoHomeLink = "/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "archive"
        name = "Blog"
        url = "/blog"
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/about"
